name: BetterEssentials
version: ${project.version}
main: io.github.si1kn.be.BEPlugin
authors: [ Si1kn ]
description: Better Essentials
website: si1kn.github.io/be.html

commands:
  fly:
    description: Fly
    usage: /<command>

  enderchest:
    description: opens enchest
    usage: /<command>

  day:
    description: sets time to day
    usage: /<command>
  night:
    description: sets time to night
    usage: /<command>

  chat:
    description: disables / enables chat
    usage: /<command>

  report:
    description: report players
    usage: /<command>